# 开发环境配置
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  # 开发环境关闭thymeleaf的缓存
#  thymeleaf:
#    cache: false
# 日志配置
logging:
  file: logs/neko-dev.log
  level:
    root: info
    com.wzz: debug
server:
  port: 8090
